Week12/create update params
koryun23/java-lvl1 pull request #105
Opened 2022-04-02 13:12 UTC by koryun23

2022-04-05 07:46 UTC, gevorgyanarman requested changes

2022-04-05 07:46 UTC, gevorgyanarman commented on src/main/com/aca/homework/week12/params/UserCreateParams.java
> +    private String username;
let's make this field final

2022-04-05 18:56 UTC, gevorgyanarman commented on src/main/com/aca/homework/week12/params/UserCreateParams.java
> +    private String username;
In that case do not use setters

2022-04-09 13:02 UTC, koryun23 commented
done

2022-04-09 19:48 UTC, merged