The solution of the 'clickable' problem
koryun23/java-lvl1 pull request #61
Opened 2022-02-23 20:17 UTC by koryun23

2022-02-26 13:22 UTC, gevorgyanarman requested changes

2022-02-26 13:22 UTC, gevorgyanarman commented on src/main/com/aca/homework/week7/clickable/AbstractClickable.java
> +public abstract class AbstractClickable implements Clickable{
the txt file is missing

2022-02-27 06:16 UTC, gevorgyanarman requested changes

2022-02-27 06:16 UTC, gevorgyanarman commented on src/main/com/aca/homework/week7/clickable/AbstractClickable.java
> +public abstract class AbstractClickable implements Clickable{
please format the code (ctrl +alt+shift+L)

2022-02-27 06:16 UTC, gevorgyanarman commented on src/main/com/aca/homework/week7/clickable/AbstractClickable.java
> +    Action action;
should be private

2022-02-27 06:16 UTC, gevorgyanarman commented on src/main/com/aca/homework/week7/clickable/Button.java
> +    String name;
should be private, also you can move the name to Abstract class

2022-03-01 19:46 UTC, gevorgyanarman requested changes

2022-03-01 19:46 UTC, gevorgyanarman commented on src/main/com/aca/homework/week7/clickable/AbstractClickable.java
> +    public String getName() {
just implement the name() method and do not provide getName()

2022-03-04 10:09 UTC, koryun23 commented
done

2022-03-05 10:24 UTC, gevorgyanarman requested changes

2022-03-05 10:24 UTC, gevorgyanarman commented on src/main/com/aca/homework/week7/clickable/Button.java
> +    public String name() {
please remove the name method from this class

2022-03-06 19:26 UTC, koryun23 commented
done

2022-03-09 19:55 UTC, merged