The solution of the 'payment service' problem
koryun23/java-lvl1 pull request #65
Opened 2022-02-27 10:18 UTC by koryun23

2022-03-01 19:48 UTC, gevorgyanarman requested changes

2022-03-01 19:48 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/payment/service/PaymentService.java
> +    public static int sleep() {
make this method private

2022-03-01 19:48 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/payment/service/Result.java
> +    public static Result resultOf(int time, int pay) {
no need to create a static factory here

2022-03-04 10:09 UTC, koryun23 commented
done

2022-03-05 10:32 UTC, gevorgyanarman requested changes

2022-03-05 10:32 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/payment/service/PaymentService.java
> +    private static int sleep() {
please reorder methods. first should be public methods then private ones

2022-03-05 10:32 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/payment/service/PaymentServiceTest.java
> +    private Result result;
there is no need to keep Result as a global variable.

2022-03-05 10:32 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/payment/service/PaymentServiceTest.java
> +        for(Annotation annotation : annotations){
please format the code

2022-03-06 19:32 UTC, koryun23 commented
done

2022-03-11 06:13 UTC, merged