The solution of the 'car repository' problem
koryun23/java-lvl1 pull request #66
Opened 2022-02-27 11:32 UTC by koryun23

2022-03-01 19:50 UTC, gevorgyanarman requested changes

2022-03-01 19:50 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/car/repository/CarRepository.java
> +        if(findByVin(car.getVin()) != null){
the update is not implemented if the vin already exists

2022-03-01 19:50 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/car/repository/CarRepositoryTest.java
> +        testSubject.save(car);
just write testSubject.save(new Car("abcd1234", 2007, 3))

2022-03-06 20:04 UTC, koryun23 commented
done

2022-03-11 06:12 UTC, gevorgyanarman requested changes
please do the change and merge the pull request

2022-03-11 06:12 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/car/repository/Car.java
> +    public void setOwnersCount(int ownersCount) {
someone can set a negative number here.

2022-03-12 08:42 UTC, merged