The solution of the 'random generator' problem
koryun23/java-lvl1 pull request #67
Opened 2022-02-28 12:39 UTC by koryun23

2022-03-01 19:44 UTC, gevorgyanarman requested changes

2022-03-01 19:44 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/random/generator/Result.java
> +    public static Result resultOf(String text, double duration) {
no need to create a static factory. the static factory is not better than the constructor in this case.

2022-03-01 19:44 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/random/generator/HighPerformanceRandomStringGeneratorTest.java
> +    private HighPerformanceRandomStringGenerator testSubject;
please add a new line

2022-03-01 19:44 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/random/generator/RandomStringGenerator.java
> +    boolean isLengthValid(int length);
let's make this a private method inside the implementations

2022-03-01 19:44 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/random/generator/HighPerformanceRandomStringGeneratorTest.java
> +        boolean containsErrorString = "error".equals(result.getText());
please use assertEquals instead of this

2022-03-01 19:44 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/random/generator/HighPerformanceRandomStringGeneratorTest.java
> +        assertTrue(containsErrorString && durationIs0);
better to use 2 different lines and assert them independently

2022-03-04 10:10 UTC, koryun23 commented
done

2022-03-05 10:25 UTC, merged