The solution of the 'credit card' problem
koryun23/java-lvl1 pull request #68
Opened 2022-03-01 17:03 UTC by koryun23

2022-03-01 19:40 UTC, gevorgyanarman requested changes

2022-03-01 19:40 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/credit/card/PaymentServiceTest.java
> +    PaymentService testSubject;
let's make this private

2022-03-01 19:40 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/credit/card/PaymentServiceTest.java
> +    public void setUp(){
please format the code (ctrl +alt+ shift +L)

2022-03-01 19:40 UTC, gevorgyanarman commented on src/test/com/aca/homework/week8/credit/card/PaymentServiceTest.java
> +        while(countOfPayments < 3){
just call the pay method 3 times without the lopp

2022-03-01 19:40 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/credit/card/CreditCard.java
> +public class CreditCard {
the txt file is missing

2022-03-04 10:10 UTC, koryun23 commented
done

2022-03-05 10:23 UTC, gevorgyanarman requested changes

2022-03-05 10:23 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/credit/card/CreditCard.java
> +    public void setNumber(int number) {
the credit card number can not be changed. please remove it

2022-03-05 10:23 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/credit/card/InsufficientBalanceException.java
> +public class InsufficientBalanceException extends RuntimeException{
please format the code

2022-03-05 10:23 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/credit/card/PaymentService.java
> +            throw new InsufficientBalanceException("\n"+creditCard.toString() + "\ncould not transfer $" + amountToBePaid + ", because the balance($" + creditCard.getBalance() + ") is less than the a
please move the exception text template to the exception constructor

2022-03-06 19:36 UTC, koryun23 commented
done

2022-03-10 07:31 UTC, gevorgyanarman requested changes
please do the minor fix and merge the pull request

2022-03-10 07:31 UTC, gevorgyanarman commented on src/main/com/aca/homework/week8/credit/card/CreditCard.java
> +        this.balance = balance;
please add validations, someone can set negative balance

2022-03-10 13:33 UTC, koryun23 commented
added the validation and a test for that

2022-03-10 13:33 UTC, koryun23 commented
added the validation and a test for that

2022-03-10 13:33 UTC, merged