the solution of the 'enum list' problem
koryun23/java-lvl1 pull request #84
Opened 2022-03-15 20:18 UTC by koryun23

2022-03-16 12:59 UTC, gevorgyanarman requested changes

2022-03-16 13:20 UTC, koryun23 commented
modified

2022-03-17 19:56 UTC, gevorgyanarman requested changes

2022-03-17 19:56 UTC, gevorgyanarman commented on src/main/com/aca/homework/week10/enums/list/PhoneModel.java
> +    public abstract List<String> cameras();
let's create a getter method and pass the value via constructor

2022-03-18 15:05 UTC, koryun23 commented
modified

2022-03-19 12:56 UTC, merged