the solution of the 'user mapper' problem
koryun23/java-lvl1 pull request #87
Opened 2022-03-16 19:33 UTC by koryun23

2022-03-17 19:55 UTC, gevorgyanarman requested changes

2022-03-17 19:55 UTC, gevorgyanarman commented on src/test/com/aca/homework/week10/mapper/DefaultUserMapperTest.java
> +        UserMapper mapper = new DefaultUserMapper();
please create test subject in before each method

2022-03-17 19:55 UTC, gevorgyanarman commented on src/test/com/aca/homework/week10/mapper/DefaultUserMapperTest.java
> +        Assertions.assertEquals(user.getFirstName(), mapper.map(user).getFirstName());
mapper.map should be invoked only once

2022-03-17 19:55 UTC, gevorgyanarman commented on src/test/com/aca/homework/week10/mapper/DefaultUserMapperTest.java
> +        Assertions.assertEquals(user.getUsername(), mapper.map(user).getUsername());
assert that the result.getUsername is equal to concrete string value not another variable

2022-03-18 14:57 UTC, koryun23 commented
modified the unittest

2022-03-19 13:02 UTC, gevorgyanarman requested changes

2022-03-19 13:02 UTC, gevorgyanarman commented on src/test/com/aca/homework/week10/mapper/DefaultUserMapperTest.java
> +    private UserModel testSubject;
the test subject should be UserMapper not a UserModel

2022-03-20 08:39 UTC, koryun23 commented
done

2022-03-20 08:51 UTC, merged