The solution of the 'unique cars' problem
koryun23/java-lvl1 pull request #95
Opened 2022-03-24 13:55 UTC by koryun23

2022-03-25 18:44 UTC, gevorgyanarman requested changes

2022-03-25 18:44 UTC, gevorgyanarman commented on src/main/com/aca/homework/week11/unique/cars/Car.java
> +        if(result == 0){
please format the code

2022-03-25 18:44 UTC, gevorgyanarman commented on src/main/com/aca/homework/week11/unique/cars/UniqueCars.java
> +        Set<Car> cars = new HashSet<>();
to have sorted set of cars you should use tree set

2022-03-25 18:44 UTC, gevorgyanarman commented on src/main/com/aca/homework/week11/unique/cars/Result.java
> +public class Result {
not sure that we need this class if you use sorted set instead of hash set

2022-03-26 09:37 UTC, koryun23 commented
modified

2022-03-28 05:52 UTC, gevorgyanarman requested changes

2022-03-28 05:52 UTC, gevorgyanarman commented on src/main/com/aca/homework/week11/unique/cars/UniqueCars.java
> +                if(result == 0){
please format the code

2022-03-28 05:52 UTC, gevorgyanarman commented on src/main/com/aca/homework/week11/unique/cars/UniqueCars.java
> +        Set<Car> cars = new TreeSet<>(new Comparator<Car>() {
let's create a nested private static comparator implementation class

2022-03-28 05:52 UTC, gevorgyanarman commented on src/main/com/aca/homework/week11/unique/cars/UniqueCars.java
> +    private static String allCarsToString(Set<Car> cars) {
here you load your set in a string object which is not efficient. instead you could just print each element in a loop

2022-03-31 07:45 UTC, koryun23 commented
done

2022-04-05 18:59 UTC, merged